import Head from 'next/head'
import React from 'react'

const Account = () => {
  return (
    <>
        <Head>
            <title>Account Page</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>
            User Account Page
        </h1>
    </>
  )
}

export default Account